// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyFlipperSolo.Data;

#nullable disable

namespace SkyFlipperSolo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108172214_Phase1_EnchantmentsAndPriceHistory")]
    partial class Phase1_EnchantmentsAndPriceHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyFlipperSolo.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AnvilUses")
                        .HasColumnType("smallint");

                    b.Property<string>("AuctioneerId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Bin")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlatenedNBTJson")
                        .HasColumnType("text");

                    b.Property<long>("HighestBidAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ItemCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Reforge")
                        .HasColumnType("integer");

                    b.Property<long?>("SoldPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StartingBid")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Texture")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<long>("UId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("End");

                    b.HasIndex("Tag");

                    b.HasIndex("UId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("Status", "End");

                    b.HasIndex("Tag", "End");

                    b.HasIndex("Bin", "Status", "End");

                    b.HasIndex("Tag", "Tier", "Reforge");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Enchantment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId", "Type");

                    b.ToTable("Enchantments");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Flip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MedianPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean");

                    b.Property<long>("Profit")
                        .HasColumnType("bigint");

                    b.Property<double>("ProfitPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("integer");

                    b.Property<long>("TargetPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("FoundAt");

                    b.HasIndex("NotificationSent");

                    b.ToTable("Flips");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.FlipOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuctionUuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("CurrentPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EstimatedProfit")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemTag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long>("MedianPrice")
                        .HasColumnType("bigint");

                    b.Property<double>("ProfitMarginPercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AuctionUuid");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("ProfitMarginPercent");

                    b.ToTable("FlipOpportunities");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.ItemPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AveragePrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemTag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long>("LowestBIN")
                        .HasColumnType("bigint");

                    b.Property<long>("MedianPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSales")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ItemTag", "Date")
                        .IsUnique();

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Enchantment", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.Auction", "Auction")
                        .WithMany("Enchantments")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Flip", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Auction", b =>
                {
                    b.Navigation("Enchantments");
                });
#pragma warning restore 612, 618
        }
    }
}
