// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyFlipperSolo.Data;

#nullable disable

namespace SkyFlipperSolo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260111204331_AddValueBreakdownToFlips")]
    partial class AddValueBreakdownToFlips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyFlipperSolo.Models.AlternativeName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemDetailsId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ItemDetailsId");

                    b.HasIndex("Name");

                    b.ToTable("AlternativeNames");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AnvilUses")
                        .HasColumnType("smallint");

                    b.Property<string>("AuctioneerId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Bin")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlatenedNBTJson")
                        .HasColumnType("text");

                    b.Property<long>("HighestBidAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ItemCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ItemUid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int?>("NbtDataId")
                        .HasColumnType("integer");

                    b.Property<int>("Reforge")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SoldPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StartingBid")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Texture")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<long>("UId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("End");

                    b.HasIndex("ItemUid");

                    b.HasIndex("NbtDataId");

                    b.HasIndex("Tag");

                    b.HasIndex("UId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("Status", "End");

                    b.HasIndex("Tag", "End");

                    b.HasIndex("Bin", "Status", "End");

                    b.HasIndex("Tag", "Tier", "Reforge");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.AveragePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Avg")
                        .HasColumnType("double precision");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Granularity")
                        .HasColumnType("integer");

                    b.Property<string>("ItemTag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Median")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("CacheKey", "Granularity");

                    b.HasIndex("ItemTag", "Granularity");

                    b.HasIndex("CacheKey", "Timestamp", "Granularity")
                        .IsUnique();

                    b.ToTable("AveragePrices");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.BidRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<string>("BidderId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.HasIndex("Timestamp");

                    b.ToTable("BidRecords");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Enchantment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId", "Type");

                    b.ToTable("Enchantments");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Flip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MedianPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean");

                    b.Property<long>("Profit")
                        .HasColumnType("bigint");

                    b.Property<double>("ProfitPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("integer");

                    b.Property<long>("TargetPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("FoundAt");

                    b.HasIndex("NotificationSent");

                    b.ToTable("Flips");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.FlipHitCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HitCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastHitAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.HasIndex("HitCount");

                    b.HasIndex("LastHitAt");

                    b.ToTable("FlipHitCounts");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.FlipOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuctionUuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("CurrentPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EstimatedProfit")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemTag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long>("MedianPrice")
                        .HasColumnType("bigint");

                    b.Property<double>("ProfitMarginPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("ValueBreakdown")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionUuid");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("ProfitMarginPercent");

                    b.ToTable("FlipOpportunities");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.ItemDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("FallbackCategory")
                        .HasColumnType("integer");

                    b.Property<int?>("FallbackTier")
                        .HasColumnType("integer");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MinecraftType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("ItemDetails");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NBTKey", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("KeyName")
                        .IsUnique();

                    b.ToTable("NBTKeys");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NBTLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short?>("KeyId")
                        .HasColumnType("smallint");

                    b.Property<int?>("ValueId")
                        .HasColumnType("integer");

                    b.Property<long?>("ValueNumeric")
                        .HasColumnType("bigint");

                    b.Property<string>("ValueString")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("ValueId");

                    b.HasIndex("Key", "ValueNumeric");

                    b.HasIndex("Key", "ValueString");

                    b.HasIndex("KeyId", "ValueId");

                    b.HasIndex("KeyId", "ValueNumeric");

                    b.HasIndex("KeyId", "ValueString");

                    b.ToTable("NBTLookups");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NBTValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("KeyId")
                        .HasColumnType("smallint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("KeyId", "Value")
                        .IsUnique();

                    b.ToTable("NBTValues");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NbtData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("NbtData");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.AlternativeName", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.ItemDetails", "ItemDetails")
                        .WithMany("AlternativeNames")
                        .HasForeignKey("ItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDetails");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Auction", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.NbtData", "NbtData")
                        .WithMany()
                        .HasForeignKey("NbtDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NbtData");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.BidRecord", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Enchantment", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.Auction", "Auction")
                        .WithMany("Enchantments")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Flip", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NBTLookup", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.Auction", "Auction")
                        .WithMany("NBTLookups")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyFlipperSolo.Models.NBTKey", "NBTKey")
                        .WithMany("NBTLookups")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkyFlipperSolo.Models.NBTValue", "NBTValue")
                        .WithMany("NBTLookups")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Auction");

                    b.Navigation("NBTKey");

                    b.Navigation("NBTValue");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NBTValue", b =>
                {
                    b.HasOne("SkyFlipperSolo.Models.NBTKey", "NBTKey")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NBTKey");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.Auction", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Enchantments");

                    b.Navigation("NBTLookups");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.ItemDetails", b =>
                {
                    b.Navigation("AlternativeNames");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NBTKey", b =>
                {
                    b.Navigation("NBTLookups");
                });

            modelBuilder.Entity("SkyFlipperSolo.Models.NBTValue", b =>
                {
                    b.Navigation("NBTLookups");
                });
#pragma warning restore 612, 618
        }
    }
}
